// Generated by tools/generate_api_types.py from the FastAPI OpenAPI schema.
// Do not edit by hand: run `python tools/generate_api_types.py` instead.
// `--check` in CI fails when this file no longer matches the published schema.

export interface CatalogItemDTO {
  id: string;
  name: string;
  category?: string;
  price?: number;
  description?: string;
  image?: string;
  prep_time_minutes?: number;
  nutrition?: string;
  price_note?: string;
  availability_note?: string;
  aliases?: Array<string>;
  retired?: boolean;
}

export interface CatalogItemListDTO {
  items: Array<CatalogItemDTO>;
  categories: Array<string>;
}

export interface CatalogItemWriteDTO {
  name?: string | null;
  category?: string | null;
  price?: number | null;
  description?: string | null;
  image?: string | null;
  prep_time_minutes?: number | null;
  nutrition?: string | null;
  price_note?: string | null;
  availability_note?: string | null;
  aliases?: Array<string> | null;
}

export interface ServicePeriodWindowDTO {
  start?: string;
  end?: string;
}

export interface CatalogAvailabilityRowDTO {
  id: string;
  name?: string;
  category?: string;
  status?: "normal" | "low_stock" | "sold_out" | "disabled";
  time_unavailable?: boolean;
}

export interface CatalogAvailabilityDTO {
  service_period?: string;
  configured_service_period?: string;
  service_periods?: Record<string, ServicePeriodWindowDTO>;
  items: Array<CatalogAvailabilityRowDTO>;
}

export interface CatalogAvailabilityCommandDTO {
  service_period?: string | null;
  service_periods?: Record<string, ServicePeriodWindowDTO> | null;
  sold_out_item_ids?: Array<string>;
  low_stock_item_ids?: Array<string>;
  disabled_item_ids?: Array<string>;
}
