#!/usr/bin/env python3
"""Emit TypeScript types from the FastAPI OpenAPI schema.

Hand-written frontend contracts drift from the backend silently: nothing fails
when a field is renamed on one side only, so the mismatch is found by a
customer rather than by CI. These types are generated from the schema the
server actually publishes, and `--check` fails when the committed file no
longer matches it.

Usage:
    python tools/generate_api_types.py            # write the file
    python tools/generate_api_types.py --check    # fail if it would change
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
OUTPUT = REPO_ROOT / "UI_API" / "frontend" / "shared" / "contracts" / "api-v1-catalog.ts"


def _find_ui_api_root() -> Path:
    """Locate the application package.

    The generator runs both from a checkout and from inside the test image,
    where the repository is not laid out the same way, so the app is found
    rather than assumed.
    """

    candidates = [REPO_ROOT / "UI_API", Path.cwd(), *Path.cwd().parents]
    for candidate in candidates:
        if (candidate / "main.py").is_file() and (candidate / "backend").is_dir():
            return candidate
        nested = candidate / "UI_API"
        if (nested / "main.py").is_file() and (nested / "backend").is_dir():
            return nested
    raise SystemExit("could not locate UI_API/main.py from this working directory")

#: Only the catalog capability's published DTOs. Generating every schema would
#: publish internal request models the frontend has no business knowing.
EXPORTED_SCHEMAS = (
    "CatalogItemDTO",
    "CatalogItemListDTO",
    "CatalogItemWriteDTO",
    "CatalogAvailabilityRowDTO",
    "CatalogAvailabilityDTO",
    "CatalogAvailabilityCommandDTO",
)

HEADER = """// Generated by tools/generate_api_types.py from the FastAPI OpenAPI schema.
// Do not edit by hand: run `python tools/generate_api_types.py` instead.
// `--check` in CI fails when this file no longer matches the published schema.
"""


def _load_schemas() -> dict:
    # The schema is a property of the code, not of any deployment, so the
    # generator pins the same substrate the contract tests use rather than
    # inheriting whatever database the caller's environment points at.
    os.environ.update(
        APP_ENV="test",
        DATABASE_BACKEND="sqlite",
        RUNTIME_DATA_ROOT=os.environ.get("RUNTIME_DATA_ROOT", "/tmp/project-2026-openapi"),
    )
    for leaked in ("DATABASE_URL", "MIGRATION_DATABASE_URL", "DATABASE_URL_FILE", "MIGRATION_DATABASE_URL_FILE"):
        os.environ.pop(leaked, None)

    ui_api_root = _find_ui_api_root()
    sys.path.insert(0, str(ui_api_root / "backend"))
    sys.path.insert(0, str(ui_api_root))
    from main import app  # noqa: PLC0415

    return app.openapi()["components"]["schemas"]


def _ts_type(schema: dict, schemas: dict) -> str:
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    if "anyOf" in schema:
        parts = [_ts_type(option, schemas) for option in schema["anyOf"]]
        # Pydantic writes `T | None` as anyOf[T, null]; TypeScript spells that `| null`.
        return " | ".join(dict.fromkeys(parts))
    if "const" in schema:
        return f'"{schema["const"]}"'
    if "enum" in schema:
        return " | ".join(f'"{value}"' for value in schema["enum"])
    kind = schema.get("type")
    if kind == "array":
        return f"Array<{_ts_type(schema.get('items', {}), schemas)}>"
    return {
        "string": "string",
        "integer": "number",
        "number": "number",
        "boolean": "boolean",
        "null": "null",
        "object": "Record<string, unknown>",
    }.get(kind, "unknown")


def _render(name: str, schemas: dict) -> str:
    schema = schemas[name]
    required = set(schema.get("required", []))
    lines = [f"export interface {name} {{"]
    for field, definition in schema.get("properties", {}).items():
        optional = "" if field in required else "?"
        lines.append(f"  {field}{optional}: {_ts_type(definition, schemas)};")
    lines.append("}")
    return "\n".join(lines)


def render_all() -> str:
    schemas = _load_schemas()
    missing = [name for name in EXPORTED_SCHEMAS if name not in schemas]
    if missing:
        raise SystemExit(f"schema no longer published: {', '.join(missing)}")
    blocks = [_render(name, schemas) for name in EXPORTED_SCHEMAS]
    return HEADER + "\n" + "\n\n".join(blocks) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail instead of writing")
    parser.add_argument(
        "--stdout",
        action="store_true",
        help="print instead of writing, so the schema can be read from inside a container",
    )
    args = parser.parse_args()

    rendered = render_all()
    if args.stdout:
        sys.stdout.write(rendered)
        return 0
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != rendered:
            print(f"{OUTPUT.relative_to(REPO_ROOT)} is stale; run tools/generate_api_types.py", file=sys.stderr)
            return 1
        return 0

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
